pluginGroup = dev.yamlix
pluginName = yamlix
pluginVersion = 0.1.0

# IntelliJ IDEA Community 2025.2.x -> build branch 252
platformType = IC
platformVersion = 2025.2.6.3
pluginSinceBuild = 252

kotlin.stdlib.default.dependency = false
org.gradle.configuration-cache = true
org.gradle.caching = true
org.gradle.jvmargs = -Xmx3g -XX:MaxMetaspaceSize=1g
